Repository vr4vet/Blue-Sector, pull requests merged in 2025-02, with the labels that each got.

#764 Bleeding guidance
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/BleedingStationGuide.asset
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/DialogueTrees.meta
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/DialogueTrees/BleedingInstruction.asset
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/DialogueTrees/BleedingInstruction.asset.meta
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/DialogueTrees/BleedingStationDialogue.asset
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/DialogueTrees/BleedingStationDialogue.asset.meta
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/DialogueTrees/VideoDialogue.asset
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/DialogueTrees/VideoDialogue.asset.meta
  Assets/FishFactory/Resources/Prefabs/NPC/BleedingStation/FactoryWorkerFrank.asset
  Assets/FishFactory/Scenes/BleedingStation.unity
  Assets/FishFactory/Scenes/BleedingStation/NavMesh.asset
  Assets/FishFactory/Scenes/BleedingStation/NavMesh.asset.meta
  Assets/FishFactory/Scripts/StopConveyorButton.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Assets/VR4VET/Components/NPC/Scripts/AnimationControllers/PointingScript.cs
  Assets/VR4VET/Components/NPC/Scripts/DialogueTree/DialogueBoxController.cs
  Assets/VR4VET/Components/NPC/Scripts/NPC.cs
  Assets/VR4VET/Components/NPC/Scripts/NPCSpawner.cs
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/ProjectSettings.asset
Labels: improvement

#778 Refactored fish anti-stretch script and apply mechanism in all relevant scenes
  Assets/FishFactory/Resources/Prefabs/Fish/FishFactoryBadFish.prefab
  Assets/FishFactory/Resources/Prefabs/Fish/FishFactorySalmon.prefab
  Assets/FishFactory/Scenes/BleedingStation.unity
  Assets/FishFactory/Scenes/QAStation.unity
  Assets/FishFactory/Scripts/DropWhenStretched.cs
  Assets/FishFactory/Scripts/StopConveyorButton.cs
  Assets/FishFactory/Scripts/WhichJointGrabbed.cs
  Assets/FishWelfare/Prefabs/salmon_rigged_1lice_2gill.prefab
  Assets/FishWelfare/Prefabs/salmon_rigged_4lice_1gill.prefab
  Assets/FishWelfare/Prefabs/salmon_rigged_4lice_4gill.prefab
  Assets/FishWelfare/Prefabs/salmon_rigged_5lice_5gill.prefab
  Assets/FishWelfare/Scenes/FishWelfare.unity
  Assets/Laboratory/Prefabs/Fish/LaboratoryFish.prefab
Labels: bug, improvement

#779 Ability to deactivate tooltips with tag
  Assets/FishFactory/Scenes/HSERoom.unity
  Assets/VR4VET/Components/ControllerToolTips/Scripts/ControllerTooltipManager.cs
  ProjectSettings/TagManager.asset
Labels: improvement

#802 Add constraints for pointing
  Assets/Laboratory/Scenes/Laboratory.unity
  Assets/VR4VET/Components/NPC/Animations/Gestures/Pointing.anim
  Assets/VR4VET/Components/NPC/Animations/Gestures/Pointing.anim.meta
  Assets/VR4VET/Components/NPC/Animations/Gestures/X Bot@Pointing.fbx
  Assets/VR4VET/Components/NPC/Animations/Gestures/X Bot@Pointing.fbx.meta
  Assets/VR4VET/Components/NPC/Animations/NPCHumanoidAnimationController.controller
  Assets/VR4VET/Components/NPC/Scripts/AnimationControllers/AnimationConstraintsController.cs
  Assets/VR4VET/Components/NPC/Scripts/AnimationControllers/PointingScript.cs
  Assets/VR4VET/Components/NPC/Scripts/SetCharacterModel.cs
Labels: enhancement
